# Generated by Django 4.0.3 on 2022-04-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=80)),
                ('LastName', models.CharField(max_length=80)),
                ('Password', models.CharField(max_length=20)),
                ('address2', models.TextField(null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Giza', 'Giza'), ('Cairo', 'Cairo')], max_length=50)),
            ],
        ),
    ]
