# Generated by Django 4.0.3 on 2022-04-29 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email_address',
            field=models.EmailField(max_length=80, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza')], max_length=50),
        ),
    ]
