# Generated by Django 4.0.3 on 2022-04-29 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_login_email_address_alter_login_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email_address',
            field=models.EmailField(max_length=80, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
