# Generated by Django 4.0.3 on 2022-04-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_login_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.CharField(choices=[('Giza', 'Giza'), ('Cairo', 'Cairo')], max_length=50),
        ),
    ]
