# Generated by Django 4.0.3 on 2022-04-29 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_signup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email_address',
            field=models.EmailField(max_length=120, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza')], max_length=50),
        ),
    ]
