# Generated by Django 4.0.3 on 2022-04-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='address',
            field=models.CharField(default='none', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.CharField(choices=[('Giza', 'Giza'), ('Cairo', 'Cairo')], max_length=50),
        ),
    ]
