# Generated by Django 4.0.3 on 2022-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_signup_address_alter_signup_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
