# Generated by Django 4.0.3 on 2022-05-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_signup_address_alter_signup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza')], max_length=50),
        ),
    ]
