# Generated by Django 4.0.3 on 2022-05-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_signup_state'),
        ('users', '0008_signup_email'),
    ]

    operations = [
    ]
