# Generated by Django 4.0.3 on 2022-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0008_alter_signup_state_0008_signup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.CharField(choices=[('Giza', 'Giza'), ('Cairo', 'Cairo')], max_length=50),
        ),
    ]
