# Generated by Django 4.0.3 on 2022-04-29 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BENCHES', 'BENCHES'), ('TABLES', 'TABLES')], default='wooden bench', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='when',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(default='Foldable paper'),
        ),
    ]
