# Generated by Django 4.0.3 on 2022-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='body',
            field=models.TextField(),
        ),
    ]
