# Generated by Django 4.0.3 on 2022-05-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_order_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='Foldable paper')),
                ('category', models.CharField(choices=[('BENCHES', 'BENCHES'), ('TABLES', 'TABLES')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
