# Generated by Django 4.0.3 on 2022-05-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
