# Generated by Django 4.0.3 on 2022-05-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_order_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
