# Generated by Django 4.0.3 on 2022-05-30 00:30

from django.conf import settings
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_remove_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(home.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
